import type { Metadata } from "next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
import { ApolloWrapper } from "./lib/graphql"
import Header from "./components/Header"
import "./globals.css"

export const metadata: Metadata = {
  title: "Juco Football Stats",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen bg-slate-100 border-2 border-green-500'>
        <ApolloWrapper>
          <Header />
          {children}
          <SpeedInsights />
          <Analytics />
        </ApolloWrapper>
      </body>
    </html>
  )
}
