import type { Metadata } from "next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
import Header from "./components/Header"
import "./globals.css"
import Footer from "./components/Footer"

export const metadata: Metadata = {
  title: "Home | Juco Football Archive",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen bg-slate-100 border-2 border-green-500'>
        <Header />
        <main className='flex flex-col flex-grow w-100 border-solid border-2 border-black bg-slate-200 p-2 m-2'>
          {children}
        </main>
        <Footer />
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  )
}
